/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mym;

import org.mym.config.AppConfig;

public class App {

    public static void main(String[] args) {
        new AppConfig().run();
    }
}
