name: Gradle build project - Spring-xml-context
on: workflow_dispatch
# on: pull_request

jobs:

  build_spring-xml-context_project_in_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Show all directories
        run: Get-ChildItem -Recurse -Force
      - name: Run Gradle script - build
        run: |
          cd spring-xml-context
          .\gradlew.bat build

  build_spring-xml-context_project_in_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Show all directories
        run: ls -Rla
      - name: Run Gradle script - build
        run: |
          cd spring-xml-context
          chmod 777 ./gradlew
          ./gradlew build
  
  build_spring-xml-context_project_in_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Show all directories
        run: ls -Rla
      - name: Run Gradle script - build
        run: |
          cd spring-xml-context
          chmod 777 ./gradlew
          ./gradlew build
