name: Gradle build project
on: workflow_dispatch
# on: pull_request

jobs:

  build_spring-xml-context_project_in_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Print list of directory
        run: Get-ChildItem -Force
      - name: Run Gradle script
        run: /spring-xml-context/gradlew.bat help

#   path_project_linux:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3.5.3
#       - name: Print list of directory
#         run: ls -la
#       - name: Setup Java JDK
#         uses: actions/setup-java@v3.12.0
#         with:
#           distribution: 'liberica'
#           java-version: '17'
#       - name: Setup and execute Gradle 'build' task
#         uses: gradle/gradle-build-action@v2
#         with:
#           arguments: build
#       - name: Run Gradle script
#         run: ./gradlew help
  
#   path_project_macos:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3.5.3
#       - name: Print list of directory
#         run: ls -la
#       - name: Setup Java JDK
#         uses: actions/setup-java@v3.12.0
#         with:
#           distribution: 'liberica'
#           java-version: '17'
#       - name: Setup and execute Gradle 'build' task
#         uses: gradle/gradle-build-action@v2
#         with:
#           attributes: build
