/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.mym.config;

import org.junit.jupiter.api.Test;
import org.mym.domain.Question;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import java.util.Collection;

import static org.junit.jupiter.api.Assertions.assertFalse;

class ProcessConfigTest {
    @Test void parsedQuestionsHasACollection() {
        ProcessConfig.CONFIG.run("/context.xml", ClassPathXmlApplicationContext::new);
        Collection<Question> questions = ProcessConfig.CONFIG.getQuestions();
        assertFalse(questions.isEmpty(), "parsed questions should be not empty");
    }
}
